### PR TITLE
Added Rotation

### PR DESCRIPTION
**Pull request by burtonwilliamt**
Hey, I needed rotation to work for my current install, so I added the code here.  I made sure to validate the input during the config parsing. I also had to sort of change the way that the x and y were being calculated before going into the UI. Now they are just floats between 0.0 and 1.0(ish) because for rotations I needed to invert some of them. Also, I added some defaults that seemed reasonable for my testing at least for the configuration.

I don't know if this is a general problem, or if it is something that I messed up, but after about 60 seconds of using this, the touch screen stops responding. The program doesn't crash, but it just keeps hitting continue [here](https://github.com/adafruit/Adafruit_Userspace_PiTFT/blob/b3ebbe37bb0b355d77f6df0c4424d16a3e9d2666/touchmouse.py#L164). I'd be interested in hearing thoughts on that, or if I'm not coding to your standards.

### CODE REVIEW

**Comment by burtonwilliamt** [comment]
To clarify: I have had a few instances where after tapping repeatedly, the touchmouse.py no longer seems to realize I am tapping/touching the screen.

**Comment by ladyada** [comment]
yeah touchmouse...isnt great. sorry :/ it was a half-fix for an issue that was otherwise resolved

**Comment by burtonwilliamt** [comment]
Is there a better solution than touchmouse?

**Comment by ladyada** [comment]
to what?

**Comment by burtonwilliamt** [comment]
Trying to get the touchscreen to work on newer versions of Raspian

**Comment by ladyada** [comment]
yah try this! https://forums.adafruit.com/viewtopic.php?f=50&t=124665#p630192

**Comment by burtonwilliamt** [comment]
Just tried this out, it works very well! Thank you! Should I close this PR?

**Comment by burtonwilliamt** [comment]
Also, it might help to update this page: https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/userspace-tools to point to the new script

**Comment by ladyada** [comment]
yep working on it soon soon :)

**Pull request closed without merging**
